### ISSUE TITLE
Liburing now installs in /usr/lib

### ISSUE THREAD

**Issue by JasonTaylor122** [MarkReedZ/mrloop#2]
The build script looks for liburing in /usr/local/lib.  

```
git clone https://github.com/axboe/liburing.git
cd liburing
make
sudo make install
```

Puts liburing.a in /usr/lib and mrloop's bld file looks for it in /usr/local/lib

**Comment by MarkReedZ** [comment]
Thanks for pointing this out.  I'm not accepting your PR as the bld and Makefile needed to be updated plus I modified the build to now include the liburing library in libmrloop.a so you no longer need to include both libraries in all client builds. 

Let me know if you have any problem with my changes which are in 3c12752673a393b1e121cc9888d71df658f4272b

Liburing is now defaulting to installing in /usr while mrloop defaults to /usr/local.  I'm open to anyone who thinks our Makefile should change.
