### ISSUE TITLE
echo_server does not echo

### ISSUE THREAD

**Issue by Qix-** [MarkReedZ/mrloop#4]
Trying to run the `echo_server` with the rust benchmarker results in a read error. Sure enough, using `nc localhost 12345` and typing a few lines gets me no results back to the client.

Am I missing something here?

**Comment by eecheng87** [comment]
It seems that I/O would be submitted only if the number of operation is greater than 64. Thus, single write would not issue the execution.

Here is the related logic in mrloop.c: 
> if ( num_sqes > 64 ) { io_uring_submit(loop->ring); num_sqes = 0; }
