### ISSUE TITLE
`mr_writev` calls `io_uring_submit` in batches?

### ISSUE THREAD

**Issue by aprilweet** [MarkReedZ/mrloop#6]
![image](https://user-images.githubusercontent.com/10728431/147525512-93c14698-e999-47ef-9a61-ca409dea529b.png)

Maybe the aim is improving performance, but what if no much `writev` in a short-time? Every `writev` will wait for a long time to be submitted to kernel?

**Comment by MarkReedZ** [comment]
The need to flush the submit queue has been documented using mr_writevf
